src/utils/pathResolver.ts
Pretty self-explanatory, just wanting to help make it better!
=> Fixes a typo

package.json, yarn.lock
Replace `rm` command with `rimraf` since `rm` doesn't exist on windows
=> fix: build script on windows

README.md
Update configuration src path in README.
=> docs(readme): update config src path

package.json
Pointing to the right file. `index.d.ts` does not exist.
=> fix: typings field in package.json

src/client/app/router.ts
Let the browser open the link if shift/ctrl/meta key is pressed
=> fix(router): allow open new tab with ctrl + click

src/client/theme-default/Layout.vue, src/client/theme-default/styles/layout.css
Resolve https://github.com/vuejs/vitepress/issues/76
The solution is same to VuePress.
And...
Sidebar should be closed when sidebar's contents are clicked.
I'll make another PR about this!
=> feat: close sidebsr when click outside

src/client/theme-default/styles/layout.css, src/client/theme-default/styles/vars.css
This was missing for mobile to correctly display
=> fix(sidebar): no margin on mobile

src/client/theme-default/Layout.vue, src/client/theme-default/components/NavBar.vue, src/client/theme-default/styles/layout.css
I'm not sure how do we want to add this feature on vitepress yet, so I added a slot for the moment so we can implement the searchbox on userland. This is what it looks like on vue-router-next docs
=> feat(client): add slot for a searchbar

src/client/app/composables/siteData.ts, src/client/theme-default/Layout.vue, src/client/theme-default/components/Home.vue, src/client/theme-default/styles/layout.css
=> feat(client): support homepages feature

src/client/theme-default/styles/layout.css
=> fix(client): show top part of scrollbar in sidebar

.gitignore, examples/minimal/index.md, examples/minimal/package.json
Add example setups. We may use this as E2E test base in the future. The setup is similar to how #126 is setup.
The purpose of this examples is to try, test out various build setups. For example, project with no config, project with config, with i18n, etc.
At very first, I'm adding bare minimal VitePress setup example, which only contains `index.md`.
Additional examples could be:
- With simple sidebar option.
- Multiple sidebar option.
- i18n integration.
These are the options with is hard to tweak while developing, since we need to prepare page files in different directory, and tweaking sidebar and nav config takes time. Other things like `editTextLinks`, or `nextLinks` can be tested easily by just tweaking the configs on the fly.
Full featured example could equal to VitePress docs I …
=> chore: add example project setup

src/client/theme-default/styles/code.css, src/client/theme-default/styles/layout.css, src/client/theme-default/styles/vars.css
This PR fixes the code block problem once and for all! 🏃 🏃 🏃
=> fix: make code block look prettier

src/client/theme-default/composables/activeSidebarLink.ts
fix #140
This PR refactors the active sidebar link logic. Fixes the issue #140 as well.
=> fix: fix sidebar active status not working as expected (#140)

src/client/theme-default/components/LastUpdated.vue
This PR attempts to fix the hydration mismatch.
=> fix: hydration mismatch

src/client/theme-default/config.ts
Corrected a missing s in the theme config for prevLinks and nextLinks
=> fix: prevLinks and nextLinks config type

src/client/theme-default/components/HomeHero.vue
Use` NavLink` instead of action. 
close #168
=> fix(theme): the actionLink miss withBase (#168)

src/client/theme-default/components/NavDropdownLinkItem.vue, src/client/theme-default/components/NavLink.vue, src/client/theme-default/composables/navLink.ts
Please see https://github.com/vuejs/vitepress/issues/195 for more details... (May Chinese required)
=> fix: HomeHero NavLink reactivity lost (#195)

docs/guide/deploy.md
=> docs(deploy): fix typo (#240) [skip ci]

src/node/build/build.ts
=> refactor: remove extra condition

docs/index.md
Indicate VuePress version number.
Add a link to vuepress-next.
:wink: :heart:
=> docs: refine the comparison with vuepress

src/node/config.ts
Provide a exclude option for pages scan.
=> feat: exclude option

docs/guide/markdown.md, package.json, src/node/markdown/plugins/highlight.ts
=> docs: keyword vuepress change vitepress

docs/.vitepress/config.js, docs/guide/differences-from-vuepress.md
I think `#` should be a careless little mistake, change to `##` so that sidebar will be correct.
=> docs: # default theme change ##

docs/guide/theming.md
=> docs: spell error

src/node/plugin.ts
=> chore: remove log

src/client/theme-default/components/BuySellAds.vue, src/node/build/bundle.ts
=> build: rename carbon and buysell chunks

src/client/theme-default/components/Home.vue
Close https://github.com/vuejs/vitepress/issues/346
=> fix(css): remove 720px breakpoint in home layout

package.json, src/node/markdown/markdown.ts, yarn.lock
=> feat: use `markdown-it-attrs` for markdown-it plugins

docs/guide/theming.md
Fixes minor spelling error (`shoud` -> `should`) and grammar error (missing word: `look`).
=> docs(theming.md): fix spelling and grammar errors

docs/.vitepress/config.ts
=> docs: update docsBranch

docs/guide/theming.md
remove duplicate backticks in code sample of theming
=> docs(guide): remove duplicate backticks

src/client/theme-default/composables/sideBar.ts
=> chore: fix typo

src/node/markdownToVue.ts
=> fix: always respect frontmatter title

package.json
https://github.com/vuejs/vitepress/issues/456#issuecomment-1047407711
=> fix: require at least node v14

src/client/app/router.ts, src/client/theme-default/components/LastUpdated.vue
=> fix: reset page data on 404

src/client/theme-default/components/VPContent.vue, src/client/theme-default/components/VPDoc.vue, src/client/theme-default/composables/copy-code.ts, src/client/theme-default/styles/components/vp-doc.css, src/client/theme-default/styles/vars.css, src/node/markdown/plugins/preWrapper.ts
=> feat: add copy code element (#473)

docs/config/app-configs.md, docs/guide/markdown-extensions.md, package.json, pnpm-lock.yaml, src/node/markdown/markdown.ts, src/node/shims.d.ts
Fixes #388
Maybe #201 #521 too. Need investigation. Both are no longer reproducible.
=> fix: switch to `markdown-it-toc-done-right`

src/node/markdown/plugins/component.ts
=> fix: modify `HTML_SEQUENCES` for better parsing (#638)

package.json, src/node/build/render.ts
=> fix: convert paths in dynamic imports to file urls (#671)

docs/config/theme-configs.md, src/client/theme-default/components/VPNavBarTitle.vue, types/default-theme.d.ts
close https://github.com/vuejs/vitepress/issues/637
=> feat: option to hide title in case of logo

package.json, pnpm-lock.yaml, src/node/markdownToVue.ts
=> fix: explicitly set component name (#657)

src/client/theme-default/components/VPButton.vue, src/client/theme-default/components/VPNavBarTitle.vue
fixes bug mentioned in #717 and some others
=> fix: use base in links

src/client/theme-default/components/VPFlyout.vue
=> fix(style): typo

src/client/theme-default/components/VPDoc.vue
=> fix: make page name inside VPDoc use complete path

docs/.vitepress/config.ts, docs/config/theme-configs.md, docs/guide/theme-edit-link.md, src/client/theme-default/composables/edit-link.ts, types/default-theme.d.ts
=> feat: allow custom edit links

src/client/theme-default/components/VPNavBar.vue, src/client/theme-default/components/VPNavBarSocialLinks.vue
<table><tr>
<td width="500px">
</td>
<td width="500px">
</td></tr></table>
=> fix(style): sidebar right blur notch

docs/guide/theme-homepage.md
Sidenote: VitePress is looking real slick so far. Ready to jump in and start using it 👍
=> docs: spelling error in theme-homepage.md

src/node/utils/parseHeader.ts
find 'remvoe' would to be 'remove'
=> chore: spell error

src/node/markdown/plugins/containers.ts
=> fix: allow title in containers to have markdown content

docs/guide/theme-introduction.md, src/client/theme-default/Layout.vue, src/client/theme-default/components/VPContent.vue, src/client/theme-default/components/VPDoc.vue
close https://github.com/vuejs/vitepress/issues/762
=> feat: add doc before and after slot

docs/guide/deploying.md
Disclosure: I'm a Solutions Engineer at Layer0.
=> Add Layer0 to the deployment platform

docs/guide/deploying.md
close https://github.com/vuejs/vitepress/issues/369
=> docs: add cloudflare pages deploy

src/client/shim.d.ts, src/client/theme-default/components/VPAlgoliaSearchBox.vue, src/client/theme-default/components/VPImage.vue, src/client/theme-default/components/VPNavBarMenuGroup.vue, src/client/theme-default/components/VPNavBarMenuLink.vue, src/client/theme-default/components/VPNavScreenMenuGroupSection.vue, src/client/theme-default/components/VPSidebarGroup.vue, src/client/theme-default/components/VPSidebarLink.vue, src/client/theme-default/components/VPSocialLink.vue, src/client/theme-default/components/VPSocialLinks.vue, src/client/theme-default/composables/nav.ts, src/client/theme-default/config.ts, src/client/theme-default/index.ts, src/client/theme-default/support/sidebar.ts
fixes: https://github.com/vuejs/vitepress/issues/773
=> fix(types): use `import type` for `DefaultTheme`

src/client/theme-default/components/VPSidebarGroup.vue
=> fix: watch for change in props

src/client/theme-default/Layout.vue
=> feat: add global layout slots

src/node/build/build.ts, src/node/serve/serve.ts, src/node/server.ts
=> fix: compatible with `--base` flag

src/node/markdown/markdown.ts
=> feat(markdown): allows to use custom highlight

docs/config/app-configs.md
This PR alphabetizes the configs in https://vitepress.vuejs.org/config/app-configs.html and adds `ignoreDeadLinks`.
=> docs: add ignoreDeadLinks

src/client/theme-default/components/VPTeamMembersItem.vue
=> fix(theme): change sponsor link class name to bypass adblock

src/node/markdownToVue.ts
Continue https://github.com/vuejs/vitepress/issues/822#issuecomment-1160655885
cc @brc-dd
=> chore: add workaround replacement for dead link

src/client/theme-default/Layout.vue, src/client/theme-default/components/VPDoc.vue, src/client/theme-default/composables/nav.ts, src/client/theme-default/composables/sidebar.ts
fix https://github.com/vuejs/vitepress/issues/872
=> fix(theme): close menu on route change

docs/config/theme-configs.md, docs/guide/theme-prev-next-link.md, src/client/theme-default/components/VPDocFooter.vue, src/client/theme-default/composables/prev-next.ts, types/default-theme.d.ts
fixes: #758 
closes: #763
fixes: #893
=> feat(theme): custom prev/next labels and text

docs/guide/deploying.md
=> docs: add node.js version to deployment notes

src/client/theme-default/components/VPButton.vue, src/client/theme-default/components/VPLink.vue, src/client/theme-default/support/utils.ts, src/shared/shared.ts, src/shared/tsconfig.json
=> fix: treat all URI schemes as external

src/node/markdown/plugins/image.ts
fixes #921
not sure though if this is a proper fix
=> fix: decode image src so that rollup can process it

src/node/markdownToVue.ts
=> fix(build): cache key should consider file path

src/client/theme-default/components/VPDocAsideOutline.vue
=> fix: decode href before using as query selector

src/client/theme-default/components/VPSidebar.vue
=> fix: title bar can not completely cover sidebar texts

src/client/theme-default/styles/components/vp-doc.css
=> fix: line highlighting in custom code block

docs/config/app-configs.md
=> docs: add "head" config to app-configs

src/node/build/render.ts, src/node/config.ts
x-ref: https://github.com/vuejs/vitepress/issues/670#issuecomment-1189466196
=> feat: provide `transformHtml` hook

src/client/theme-default/components/VPFooter.vue
=> feat: allow html in footer

src/node/markdown/plugins/highlight.ts
Support code highlight in uppercase, like Bash、HTML、JavaScript etc can normally build.
```
Error: No language registration JavaScript
```
=> feat(build): support code highlight in uppercase

src/client/theme-default/components/VPAlgoliaSearchBox.vue
=> fix: remove duplicate router logic

docs/config/app-configs.md
=> docs: add `outDir`

src/client/app/index.ts, src/client/theme-default/components/VPContent.vue
Signed-off-by: Roman Ondráček <ondracek.roman@centrum.cz>
=> fix(theme): fix custom Not found page rendering

src/node/plugin.ts, src/node/server.ts
Had added this in #1132, but didn't notice it was being used in test setup:
https://github.com/vuejs/vitepress/blob/main/examples/vitestSetup.ts#L156
=> chore: make recreateServer optional

src/client/theme-default/styles/components/vp-doc.css
fixes: #1169, fixes #1175
x-ref: #1152
=> fix(theme): restore styles for code blocks

src/client/theme-default/styles/components/vp-doc.css
The indent spacing is too large when displaying line numbers
=> update styles for code blocks

src/client/theme-default/components/VPNavBar.vue, src/client/theme-default/components/VPNavScreen.vue
fixes regression caused by #1168
=> fix(theme): set pointer events all on VPNavScreen

src/shared/shared.ts
change createTitle to be able to use the title within the titleTemplate like suggested in #1195 
will not break existing solution
=> feat(theme): extend titleTemplate by replacing the title

docs/guide/migration-from-vuepress.md
I just put this in the migration guide for now. Should it appear somewhere in the main docs as well?
=> docs: pointers for creating a dynamic sidebar

src/node/build/build.ts
fixes #1209 
Detailed differences: https://superuser.com/a/1291446
=> fix: use junctions in Windows

package.json, pnpm-lock.yaml, src/node/markdown/env.ts, src/node/markdown/index.ts, src/node/markdown/markdown.ts, src/node/markdown/plugins/link.ts, src/node/markdownToVue.ts
- use @mdit-vue/plugin-frontmatter
=> feat: support markdown frontmatter options

docs/guide/deploying.md
Copied descriptive text about `base` property from https://vitepress.vuejs.org/config/app-configs#base
=> docs: clarify GitHub Pages deployment instructions

src/client/app/composables/copyCode.ts
=> feat: keep display copied hint when click multiple times

package.json, pnpm-lock.yaml, src/client/app/router.ts, src/client/theme-default/Layout.vue, src/client/theme-default/index.ts, src/client/theme-default/styles/lib-override/nprogress.css, theme.d.ts
=> feat(theme-default): add page load progressbar

src/client/theme-default/index.ts, src/client/theme-default/support/utils.ts
=> fix(theme): show progress bar after delay

src/client/theme-default/components/VPSidebarLink.vue
=> fix(theme): don't nest sidebar links

docs/guide/theme-team-page.md
=> docs(theme-team-page): Fixed typo issue

src/client/theme-default/styles/base.css
=> Use pointer cursor only on enabled button

package.json, pnpm-lock.yaml
=> chore: wait for files to build before running dev docs

src/node/build/build.ts
Improving the performance by running the independent async functions in parallel ✈️.
_Sorry if I made any mistakes :(_
=> perf: render pages asynchronously

src/client/theme-default/components/VPNavBarExtra.vue
@media min-width > 768px and < 1280px
https://vui.vercel.app/
=> fix(theme): hide extra navbar when no content

src/client/theme-default/components/VPImage.vue
Signed-off-by: GurkiranSingh <gurkiransinghk@gmail.com>
- fix: Added alt attribute for the logo img
- Closes #1309 
Please, let me know if you see any issues :)
=> fix: Added alt attribute for the logo img

src/node/plugin.ts
loosely based on https://github.com/vitejs/vite/blob/main/packages/vite/src/node/server/middlewares/indexHtml.ts#L276
=> feat(build): allow using `transformIndexHtml`

src/node/server.ts
=> fix(compat): use default export of dns module

src/node/build/bundle.ts
=> fix(build): remove leading underscore from chunks

docs/guide/markdown.md, docs/guide/theme-footer.md, docs/guide/theme-team-page.md, docs/guide/what-is-vitepress.md, examples/vitestSetup.ts, src/client/theme-default/composables/sponsor-grid.ts
This PR fixes a few typos, both in the documentation and in source code.
=> docs: fixing typos

package.json, pnpm-lock.yaml
=> fix(build): ignore tsconfig target in dev

src/client/theme-default/components/VPHero.vue
=> fix(theme): make text prop of VPHero optional

docs/config/app-configs.md
See: https://github.com/vuejs/vitepress/discussions/1427#discussioncomment-3782180 .
=> feat(docs): add `srcDir` config

src/node/build/bundle.ts
=> revert: "fix(build): remove leading underscore from chunks"

src/client/app/utils.ts, src/node/build/bundle.ts, src/node/build/render.ts, src/shared/shared.ts
=> Revert "fix(build): better align server and client side filename sanitization"

src/client/app/utils.ts, src/node/build/bundle.ts, src/node/build/render.ts, src/shared/shared.ts
same as #1475, just gonna remove lookbehind for safari compat
=> fix(build): better align server and client side filename sanitization

src/client/theme-default/styles/base.css, src/client/theme-default/styles/fonts.css, src/client/theme-default/styles/vars.css, src/node/config.ts, src/node/plugin.ts, src/node/webFontsPlugin.ts
=> feat(build): add `useWebFonts` option

src/client/theme-default/components/VPSwitchAppearance.vue
=> fix(theme): use stored preference to be the value of `userPreference`

package.json, pnpm-lock.yaml, src/node/markdown/plugins/highlight.ts
reverts #1546 (fixed in upstream)
fixes #1555
=> fix(build): use addClass from shiki-processor

src/client/theme-default/styles/base.css, src/client/theme-default/styles/fonts.css
fixes https://github.com/vuejs/vitepress/pull/1531#issuecomment-1303951733
=> fix(theme): use faux italics only with web fonts

docs/config/frontmatter-configs.md, docs/guide/frontmatter.md, docs/guide/markdown.md, docs/guide/using-vue.md, docs/guide/what-is-vitepress.md, src/client/app/composables/copyCode.ts
=> fix(theme): ignore removed diff lines while copying code

src/node/plugin.ts
fixes #1608 
closes #1609 
fixes #1480
fixes #1632
fixes #297
=> fix(build): allow serving files in dev from workspace root

src/node/markdown/plugins/highlight.ts
closes #1740
Co-authored-by: Ron0115 <jayguess@qq.com>
=> fix(build): handle `-` in title of code blocks with line highlighting

docs/guide/theme-introduction.md, src/client/app/index.ts, src/client/app/ssr.ts, src/client/app/theme.ts
Co-authored-by: Nick Borko <nick.borko@gmail.com>
fixes #599
=> feat: allow `enhanceApp` to return a `Promise`

src/client/app/utils.ts
=> fix(build): handle cleanUrls without trailing slash

src/client/theme-default/styles/base.css, src/client/theme-default/styles/components/vp-doc.css
case screenshot
for example
```md
normal link 
https://img.cdn.sugarat.top/mdImg/MTY3MzM2MTM3MTExMg==673361371112
ul/ol link list
* https://img.cdn.sugarat.top/mdImg/MTY3MzM2MTM3MTExMg==673361371112
* https://img.cdn.sugarat.top/mdImg/MTY3MzM2MTM3MTExMg==673361371112
* https://img.cdn.sugarat.top/mdImg/MTY3MzM2MTM3MTExMg==673361371112
1. https://img.cdn.sugarat.top/mdImg/MTY3MzM2MTM3MTExMg==673361371112
2. https://img.cdn.sugarat.top/mdImg/MTY3MzM2MTM3MTExMg==673361371112
3. https://img.cdn.sugarat.top/mdImg/MTY3MzM2MTM3MTExMg==673361371112
```
=> fix(theme): link in list will not wrap auto

docs/config/app-configs.md, src/node/config.ts, src/node/markdownToVue.ts
=> feat(build): allow ignoring only localhost dead links

src/node/plugin.ts
=> feat(build): expose vitepress site config to vite plugins

.github/workflows/lock-threads.yml
TODO: decrease schedule to once per day after backlog has cleared.
=> chore: setup lock threads

src/client/theme-default/components/VPDocAsideOutline.vue, src/client/theme-default/composables/outline.ts, src/client/tsconfig.json, src/shared/tsconfig.json, tsconfig.json, types/default-theme.d.ts
=> feat(theme): allow removing badge text from outline

src/client/app/router.ts
Fixes #1792.
See linked issue for detailed description of bug and reproduction.
=> fix(router): avoid duplicate history entries

src/client/app/router.ts
=> fix(build): consider base when checking actual pathname

docs/guide/routing.md
Change `getting-started.md` to `guide/getting-started.md`
=> docs: update nesting example

docs/config/theme-configs.md
There are some theme configurations that are not shown in the document.
=> docs: update theme configs

src/client/theme-default/components/VPNavBarSearch.vue
Fix duplicate onMounted, also avoid performing preconnect when algolia is not enabled
=> fix(theme-default): avoid preconnect without algolia

docs/guide/deploying.md
more about the merger: https://www.datacenterdynamics.com/en/news/limelight-acquires-yahoos-edgecast-cdn-service/
=> docs: layer0 is now edgio

package.json, rollup.config.ts
Helps to debug in VSCode more easily
=> chore: generate sourcemap in dev

docs/config/theme-configs.md, src/client/theme-default/composables/sidebar.ts, types/default-theme.d.ts
=> feat(theme): support disabling aside globally

docs/guide/getting-started.md
=> revert: "docs: add linkage for `code-groups` in `getting-started`"

src/client/theme-default/components/VPHero.vue
=> feat(theme): hero image now scales in all dimensions

docs/guide/deploying.md
The steps in the original document will report an error
=> fix github pages build 403

src/client/theme-default/components/VPLink.vue, src/client/theme-default/components/VPSidebarItem.vue
=> fix(theme): show external link icon on same line

.prettierignore, docs/config/theme-config.md, docs/guide/theme-nav.md, src/client/theme-default/components/VPLink.vue, src/client/theme-default/components/VPMenuLink.vue, src/client/theme-default/components/VPNavBarMenuLink.vue, types/default-theme.d.ts
x-ref: #1599
Co-authored-by: Kev1nzh37 <kev1nzh37@gmail.com>
=> feat(theme): support custom target and rel in navbar links

src/client/theme-default/components/VPMenuGroup.vue
[codesandbox](https://codesandbox.io/p/sandbox/interesting-einstein-j6l3rc)
=> fix(theme): menu group title wrap auto

src/client/app/components/Content.ts
I was looking to change the div to main, this would add a prop to do so.
=> Add `as` to Content component.

.gitignore, .prettierignore, __tests__/e2e/vitestGlobalSetup.ts, __tests__/init/init.test.ts, __tests__/init/package.json, __tests__/init/vitest.config.ts, __tests__/init/vitestGlobalSetup.ts, package.json, pnpm-lock.yaml, src/node/cli.ts, src/node/index.ts, src/node/init/init.ts, src/node/plugin.ts, template/.vitepress/config.js, template/.vitepress/config.ts, template/.vitepress/theme/Layout.vue, template/.vitepress/theme/index.js, template/.vitepress/theme/style.css, template/api-examples.md, template/index.md, template/markdown-examples.md, tsconfig.json
=> vitepress init command

src/client/theme-default/styles/components/vp-doc.css
refs https://github.com/vuejs/vitepress/pull/1998
reproduction: https://vitepress.vuejs.org/guide/markdown#line-numbers
=> fix(theme): align number to code line

docs/guide/extending-default-theme.md, src/client/theme-default/Layout.vue, src/client/theme-default/components/VPContent.vue
=> feat(theme): add not-found layout slot

src/client/theme-default/components/VPDocOutlineDropdown.vue, src/client/theme-default/components/VPLocalNavOutlineDropdown.vue
=> fix(theme): don't show outline when no header is there

docs/guide/data-loading.md
Document the ability to get the config object inside of data loaders
=> docs: add info about getting config in loaders

docs/guide/routing.md, docs/guide/using-vue.md, docs/guide/what-is-vitepress.md
=> docs: fix typo

src/client/theme-default/components/VPLocalSearchBox.vue
This behavior aligns with Algolia Search.
=> fix(search): avoid body scroll when using local search

src/client/theme-default/components/VPLocalSearchBox.vue, src/client/theme-default/support/utils.ts, src/node/build/bundle.ts, src/node/build/render.ts, src/node/markdownToVue.ts, src/node/plugin.ts, src/node/utils/slash.ts, src/shared/shared.ts
fix https://github.com/vuejs/vitepress/issues/2244
=> fix(theme): local search showDetailedList not work in Windows

src/client/theme-default/components/VPLocalNav.vue
close https://github.com/vuejs/vitepress/issues/2258
=> feat(theme): mobile view show outline button after removing sidebar

src/client/theme-default/components/VPLocalSearchBox.vue
=> fix(theme): vitepress data not properly injected in app when use localSearch

src/node/build/buildMPAClient.ts, src/node/build/bundle.ts
=> feat: preserve user log level

.github/workflows/test.yml, src/node/markdownToVue.ts, src/node/plugin.ts
fixes #2281
closes #2307
closes #2314
=> refactor: improve error message on encountering dead links

docs/reference/default-theme-footer.md
Document Content Update, associated with https://github.com/vuejs/vitepress/issues/2340
=> docs: update footer

src/node/cli.ts, src/node/shortcuts.ts
=> feat(node): add cli shortcuts

src/client/app/router.ts
fix https://github.com/vuejs/vitepress/issues/2348
=> fix(dev): hmr not work on home page when set `base` option

src/client/theme-default/components/VPFeatures.vue
close https://github.com/vuejs/vitepress/issues/2318
=> feat(theme): home features section layout consistent

src/node/config.ts
fix https://github.com/vuejs/vitepress/issues/2394
=> fix(config): set scrollOffset to 0 is not effect

src/client/theme-default/styles/components/vp-code-group.css
=> fix(theme): adjust z-index for active code group marker

src/client/theme-default/components/VPSwitchAppearance.vue
localStorage is defined on server in Deno
=> fix(theme): use document !== undefined check for browser

package.json, pnpm-lock.yaml
close https://github.com/vuejs/vitepress/issues/2397
=> chore: remove unused devDependencies

scripts/release.js
=> fix(release): not support direct import of json in windows

src/client/theme-default/components/VPLocalSearchBox.vue
The page marked by the red box is rendered repeatedly.
=> perf(theme): reduce repeated rendering of same path page

src/client/theme-default/components/VPLocalNav.vue, src/client/theme-default/components/VPLocalNavOutlineDropdown.vue, src/client/theme-default/components/VPNavBar.vue
and hide return to top when already at top
closes #2320
=> fix(theme): properly show divider between navs

src/node/build/build.ts
=> fix(build): use rimraf to handle temp folder deletion in windows

template/.vitepress/theme/index.js
=> fix: use extends in template custom theme

src/node/serve/serve.ts
`site` as a variable name here is a bit inappropriate and not very readable.
=> refactor: rename variable name and simplify some code

docs/guide/routing.md
I am starting with Vitepress so I might be wrong with this PR, but this felt like an obvious error to me. If the code should be really different from the other code samples, maybe the documentation should mention it.
=> docs: fix code sample in the dynamic routing documentation

docs/guide/getting-started.md
=> changed wizard command for pnpm

src/client/app/index.ts, src/client/app/router.ts, src/client/theme-default/components/VPDocOutlineItem.vue, src/client/theme-default/components/VPSkipLink.vue
x-ref: https://github.com/vuejs/vitepress/issues/1039#issuecomment-1614827077
=> fix(client): don't throw on using special chars in element ids

docs/guide/using-vue.md
=> fix(docs): ComponentInHeader component is not import

src/node/markdown/plugins/snippet.ts
The original code had too many layers of nested `if` structures, and the readability was a bit poor.
=> refactor: optimize snippet markdown plugin code

src/client/theme-default/Layout.vue, src/client/theme-default/components/VPContent.vue, src/client/theme-default/components/VPDoc.vue, src/client/theme-default/components/VPFooter.vue, src/client/theme-default/components/VPLocalNav.vue, src/client/theme-default/components/VPNavBar.vue, src/client/theme-default/components/VPNavBarTitle.vue, src/client/theme-default/components/VPSidebar.vue, src/client/theme-default/composables/aside.ts
=> fix(theme): fix theme without fonts emitting inter

src/client/theme-default/components/VPSidebarItem.vue
=> fix(theme): fix sidebar's caret alignment issue with long text

docs/guide/what-is-vitepress.md, docs/index.md
This PR change the layout to include a list:
=> docs: add Vitest, UnoCSS, VitePWA and Iconify to use cases

src/node/utils/getGitTimestamp.ts
=> fix(lastUpdated): use author date instead of commit date

docs/.vitepress/config.ts, src/node/build/build.ts, src/node/build/render.ts, src/node/config.ts, src/node/siteConfig.ts
=> feat(build): add `metaChunk` option to extract metadata to separate chunk

src/node/build/build.ts, src/node/build/bundle.ts
https://github.com/sindresorhus/stdin-discarder has a bit of hacky implementation which causes issues when used with Deno (https://github.com/denoland/deno/issues/19255#issuecomment-1630104490)
=> fix(compat): disable stdin-discarder

src/node/alias.ts
reintroduces #2622 with fixed hmr (was reverted in ec6bfbd)
=> fix(build): use vue dev build when DEBUG is truthy

src/client/theme-default/styles/components/vp-code-group.css
=> fix(theme): code group tab divider not showing full-width

src/node/build/render.ts
=> fix(build): duplicate description tags with transformHead

src/client/theme-default/components/VPBadge.vue, src/client/theme-default/styles/components/vp-doc.css
closes https://github.com/vuejs/vitepress/issues/2616
=> fix(style): incorrect header anchor icon position with multline headers

src/client/theme-default/composables/langs.ts, src/node/build/generateSitemap.ts, src/node/contentLoader.ts, src/node/plugins/localSearchPlugin.ts
fix https://github.com/vuejs/vitepress/issues/2541
=> fix: remove index.html when using createContentLoader

src/client/app/composables/codeGroups.ts, src/client/theme-default/styles/components/vp-code-group.css, src/client/theme-default/styles/components/vp-doc.css, src/node/markdown/plugins/containers.ts, src/node/markdown/plugins/preWrapper.ts
Example:
````md
::: code-group
<div class="vp-block active" data-title="Preview">
Hello World
</div>
```vue [Code]
<template>
Hello World
</template>
```
:::
````
=> feat: allow html blocks inside code groups

__tests__/unit/client/theme-default/support/sidebar.test.ts, docs/.vitepress/config.ts, src/client/theme-default/support/sidebar.ts, types/default-theme.d.ts
=> feat(theme): allow setting base path in sidebar items

src/client/theme-default/components/VPSidebarItem.vue, src/client/theme-default/composables/sidebar.ts
=> fix(theme): update sidebar active link status on hash change

src/client/theme-default/components/VPFlyout.vue
=> fix(theme): close dropdown menus after an item is clicked

src/client/app/router.ts
=> fix(client): handle empty hash in links

.github/workflows/test.yml, docs/guide/deploy.md, docs/guide/getting-started.md, netlify.toml, rollup.config.ts, src/node/tsconfig.json
=> chore(build)!: drop node 16 support

src/client/theme-default/components/VPNavBar.vue
=> fix(theme): dont show transparent navbar other than home

src/node/plugin.ts
closes #2782
closes #2781
closes #2612
=> fix: restart server on theme creation/deletion

src/node/cli.ts, src/node/init/init.ts
=> fix: the terminal print message is not clear

src/client/theme-default/styles/vars.css
fix https://github.com/vuejs/vitepress/issues/2900
And I remove an unused css variable `--vp-z-index-layout-top`.
=> fix(theme): dropdown menu partially hidden by the homepage footer when it is too long

src/client/theme-default/Layout.vue, src/client/theme-default/components/VPSkipLink.vue, src/client/theme-default/composables/nav.ts
=> Revert "feat(theme): use inert to avoid traverse menus and content with keyboard"

src/client/theme-default/components/VPLocalSearchBox.vue
=> fix(theme): local search enter key with the search result

src/client/app/composables/head.ts
=> fix(client): scripts loading out of order when added through head

src/client/app/index.ts, src/client/theme-default/NotFound.vue
=> fix(client): router in invalid state after 404

docs/reference/default-theme-config.md, src/client/theme-default/components/VPDocFooterLastUpdated.vue, types/default-theme.d.ts
=> feat(theme): allow forcing site locale in last updated format

docs/reference/site-config.md, src/client/app/data.ts, src/client/theme-default/components/VPNavBarAppearance.vue, src/node/config.ts, src/node/siteConfig.ts, types/shared.d.ts
=> feat(theme): allow forcing dark mode

src/node/config.ts, src/node/contentLoader.ts, src/node/plugin.ts, src/node/plugins/dynamicRoutesPlugin.ts, src/node/shims.d.ts, src/node/siteConfig.ts
=> Revert "fix(build): respect srcExclude in content loader"

__tests__/unit/node/markdown/plugins/snippet.test.ts, src/node/markdown/plugins/snippet.ts
partial fix for #1617
TODO: add tests for this monstrous regex
=> fix(build): handle importing code snippets not having an extension

src/node/shortcuts.ts
workaround for denoland/deno#17933
might wanna consider removing setRawMode though (vitejs/vite#14342) 👀
=> fix(compat): reset setRawMode on process exit

src/client/app/router.ts, src/client/app/utils.ts
fix https://github.com/vuejs/vitepress/issues/2995
=> fix(build): consistent route.path across dev and ssr

src/client/app/composables/head.ts
=> fix(client): only update head if needed

src/client/theme-default/support/utils.ts, src/node/markdown/plugins/link.ts
=> fix: don't normalize non-html/non-http links

docs/guide/extending-default-theme.md, docs/guide/ssr-compat.md
Added also how to use jsdocs...
closes #3116
=> docs: add types for theme config

docs/guide/extending-default-theme.md
@brc-dd copy/paste from ssr entry without the `extends: DefaultTheme` and logic im my previous PR...
=> docs: update types for theme config

src/client/theme-default/components/VPAlgoliaSearchBox.vue, src/client/theme-default/components/VPLocalSearchBox.vue, src/client/theme-default/components/VPNavBarSearchButton.vue
=> fix(theme/search): prevent reactivity loss with i18n

src/node/config.ts
=> export `mergeConfig()`

src/client/theme-default/components/VPSwitchAppearance.vue
=> fix(ally): clear up confusion with the title of theme switch

docs/reference/default-theme-home-page.md
=> docs: fix htttps to http

package.json, pnpm-lock.yaml, src/client/app/router.ts, src/client/theme-default/support/utils.ts, src/node/markdown/plugins/link.ts, src/node/markdownToVue.ts, src/shared/shared.ts
Reduces chunk size by ~9K
TODO: test it out
=> perf: drop dependency on mrmime

src/client/theme-default/components/VPLocalSearchBox.vue, src/client/theme-default/without-fonts.ts, src/node/build/bundle.ts, src/shared/shared.ts
=> fix: fix theme chunking logic causing out-of-order styles

docs/zh/guide/deploy.md
Fix Chinese display problem
Before repair:
After repair:
=> fix:format issues

src/client/theme-default/without-fonts.ts
Fix: https://github.com/vuejs/vitepress/issues/3430
=> feat(theme): export VPBadge

theme.d.ts
:( Sorry, I missed the type in `theme.d.ts` in last pull request
=> fix(type): fix missed `VPBadge` type in `theme.d.ts`

src/client/app/composables/head.ts
=> fix(client): handle head orphans added in first load

docs/reference/default-theme-config.md, docs/zh/reference/default-theme-config.md
add 'x' in SocialLinkIcon list
=> fix(docs): add x SocialLinkIcon

docs/.vitepress/config/shared.ts
=> docs: replace `name` with `property`

package.json, pnpm-lock.yaml, src/node/markdown/plugins/highlight.ts
v1.0 stable should be coming in a few days
=> chore: upgrade to shiki rc

docs/zh/reference/default-theme-home-page.md
sync with https://github.com/vuejs/vitepress/commit/09030272b4a5c8f723b7e11303265f24b7481575
=> docs(zh): tweak and sync translations

src/client/app/index.ts, src/shared/shared.ts
This PR is to add `window.__VITEPRESS__`. 
It helps to detect if the current site is powered by Vitepress, referring to [here](https://github.com/vuejs/devtools-next/issues/202#issuecomment-1977781974).
=> feat: add `window.__VITEPRESS__`

docs/guide/deploy.md
Adding Stormkit as deployment platform
=> docs: add Stormkit as deployment platform

docs/reference/default-theme-config.md
update default-theme sidebar type
=> docs: update default-theme sidebar type

src/client/app/router.ts
uses the hack mentioned in https://stackoverflow.com/a/33169145/11613622
=> fix(client): don't reload page on hash change

docs/zh/guide/markdown.md
update the translation, the index here should not be translated to `索引`
=> chore: update ZH translation

.github/workflows/test.yml, src/client/theme-default/NotFound.vue, src/client/theme-default/composables/langs.ts
=> fix(theme/i18n): 404 page not showing localized text

src/node/cli.ts
=> fix(dev): multiple server instances being created when editing config too quickly

src/client/app/index.ts
=> fix(dev): match dev and prod routing behavior

src/node/markdown/plugins/restoreEntities.ts
related https://github.com/vuejs/docs/issues/2857
=> fix(markdown): entities and escapes not working properly

docs/ru/guide/sitemap-generation.md, docs/ru/reference/default-theme-search.md
Updates of ru/guide/sitemap-generation and ru/reference/default-theme-search
=> docs(ru): update translations

docs/guide/using-vue.md
Fixed VitePress capitalization
=> fix: properly capitalize VitePress

__tests__/e2e/markdown-extensions/index.md, __tests__/e2e/markdown-extensions/markdown-extensions.test.ts, __tests__/e2e/markdown-extensions/region-include.md, docs/en/guide/markdown.md, src/node/markdown/plugins/snippet.ts, src/node/utils/processIncludes.ts
=> feat(markdown): support markdown region snippet

.github/pull_request_template.md, .github/workflows/ci.yml, .github/workflows/cr-comment.yml, README.md
WIP
Some credits to https://github.com/radashi-org/radashi and https://github.com/antfu-collective/.github/blob/main/.github/PULL_REQUEST_TEMPLATE.md 😅
TODO:
=> ci: setup pkg.pr.new

.github/workflows/ci.yml
---
> [!TIP]
> The owner of this PR can publish a _preview release_ by commenting `/publish` in this PR.
=> ci: enable compact mode for pkg-pr-new

docs/zh/reference/site-config.md
=> docs: Update site-config.md

docs/en/reference/frontmatter-config.md
=> Add sample for outline

docs/zh/reference/default-theme-nav.md
Chinese translation for the custom components in the navigation bar
#4000 
---
> [!TIP]
=> docs(zh): Chinese translation for the custom components in the navigation bar

docs/zh/reference/default-theme-home-page.md
=> docs: typos

src/node/markdownToVue.ts
Regressed by c46e4b784ddb9ce3bd1cfcc3de1d1d676535cb5b.
=> Fix broken rewrites since v1.4.0

docs/public/_headers, docs/public/_redirects, netlify.toml
=> docs: redirect /guide to /guide/getting-started

docs/zh/guide/markdown.md
https://vitepress.dev/zh/guide/markdown#raw
`.postcssrc.cjs` -> `postcss.config.mjs`
---
> [!TIP]
=> docs: fix postcss configuration file path

src/client/theme-default/components/VPNavBarTitle.vue
As the title said.
close #4307
=> feat(theme): don't escape `siteTitle`

docs/en/guide/i18n.md
inBrowser was missing in the imported data.
=> i18n.md : add missing variable

docs/es/guide/i18n.md, docs/ko/guide/i18n.md, docs/pt/guide/i18n.md, docs/ru/guide/i18n.md, docs/zh/guide/i18n.md
This is a PR to finalize previous PR merged https://github.com/vuejs/vitepress/pull/4389/files
For my first PR, I didn't realize there are translations.
=> Docs i18n.md : add missing variable in translations

src/client/app/index.ts, src/node/plugin.ts
@brc-dd we need to do some manual testing to make sure this works with Vue 3.4 and below (could be explicitly installed by user)
Also let's test this for Vue and Vite docs before releasing.
=> fix: fix static content removal for lean chunks due to Vue 3.5 changes

docs/en/guide/extending-default-theme.md, docs/es/guide/extending-default-theme.md, docs/fa/guide/extending-default-theme.md, docs/ko/guide/extending-default-theme.md, docs/pt/guide/extending-default-theme.md, docs/ru/guide/extending-default-theme.md, docs/zh/guide/extending-default-theme.md
I believe the regex for the file needs to be tested against all asset files.
If this is a correct fix, I can add the fix to all other languages before this pull request is merged.
=> Fix example for loading custom font

docs/en/guide/what-is-vitepress.md, docs/es/guide/what-is-vitepress.md, docs/fa/guide/what-is-vitepress.md, docs/ko/guide/what-is-vitepress.md, docs/pt/guide/what-is-vitepress.md, docs/ru/guide/what-is-vitepress.md, docs/zh/guide/what-is-vitepress.md
Seems like VueTelescope is down and isn't in used anymore(?), so I replace it with direct search on GitHub.
N/A.
N/A
---
> [!TIP]
=> docs: update Vue telescope link

src/client/theme-default/components/VPFlyout.vue, src/client/theme-default/components/VPMenu.vue, src/client/theme-default/components/VPMenuGroup.vue, src/client/theme-default/components/VPMenuLink.vue
- use generic and reduce any
- add missing key for list
=> refactor: `VPMenu` related component use generic type for component

src/client/theme-default/Layout.vue, src/client/theme-default/components/VPHero.vue, src/client/theme-default/components/VPNav.vue, src/client/theme-default/components/VPNavScreenMenuGroupLink.vue, src/client/theme-default/components/VPNavScreenMenuLink.vue, src/client/theme-default/composables/layout.ts, src/client/theme-default/composables/nav.ts
use `InjectionKey` to get better type
=> refactor(nav,layout): use `InjectionKey`
